### ISSUE TITLE
Intégrer crashlytics

### ISSUE THREAD

**Issue by seza443** [GeoHealth/HAppi_mobile#106]
Pour capter les erreurs produites sur l'app mobile

**Comment by seza443** [comment]
```
02-28 06:32:57.976  3199  3199 D SystemWebChromeClient: http://192.168.56.1:8100/build/main.js: Line 7382 : Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
02-28 06:32:57.976  3199  3199 I chromium: [INFO:CONSOLE(7382)] "Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.", source: http://192.168.56.1:8100/build/main.js (7382)
02-28 06:32:58.052  3199  3269 I App     : WARNING: Back Button Default Behavior will be overridden.  The backbutton event will be fired!
02-28 06:32:58.162  3199  3269 D FabricPlugin: FabricPlugin called with options: ["about to send a crash for testing!"]
02-28 06:32:58.169  3199  3269 D FabricPlugin: FabricPlugin called with options: []
02-28 06:32:58.207  3199  3199 W GooglePlayServicesUtil: Google Play Store is missing.
02-28 06:32:58.207  3199  3199 D SystemWebChromeClient: http://192.168.56.1:8100/build/main.js: Line 21562 : DEVICE READY FIRED AFTER
02-28 06:32:58.208  3199  3199 I chromium: [INFO:CONSOLE(21562)] "DEVICE READY FIRED AFTER", source: http://192.168.56.1:8100/build/main.js (21562)
02-28 06:32:58.417  3199  3199 D AndroidRuntime: Shutting down VM
02-28 06:32:58.506  3199  3199 E AndroidRuntime: FATAL EXCEPTION: main
02-28 06:32:58.506  3199  3199 E AndroidRuntime: Process: com.geohealth.happi, PID: 3199
02-28 06:32:58.506  3199  3199 E AndroidRuntime: java.lang.RuntimeException: This is a crash
02-28 06:32:58.506  3199  3199 E AndroidRuntime:        at com.sarriaroman.fabric.FabricPlugin$1.run(FabricPlugin.java:120)
02-28 06:32:58.506  3199  3199 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
02-28 06:32:58.506  3199  3199 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
02-28 06:32:58.506  3199  3199 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
02-28 06:32:58.506  3199  3199 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6077)
02-28 06:32:58.506  3199  3199 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-28 06:32:58.506  3199  3199 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
02-28 06:32:58.506  3199  3199 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
02-28 06:32:58.507   596   608 W ActivityManager:   Force finishing activity com.geohealth.happi/.MainActivity
```

**Comment by seza443** [comment]
Ok so actually this is an expected behaviour when we run `(<any>window).fabric.Crashlytics.sendCrash();` :trollface:
